# Generated by Django 3.0.2 on 2021-03-13 14:22

import datetime
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('price', models.FloatField(validators=[product.models.minpricevalidator])),
                ('size', models.CharField(blank=True, max_length=3)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
